name: .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Geração do Pacote
      run: dotnet build -c Release -o out

    - name: Push no NuGet
      run: |
        cd out
        dotnet nuget push *.nupkg --api-key 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 --source "https://nuget.pkg.github.com/MatheusPetrachin/index.json" --skip-duplicate
